// COMServer.idl : IDL source for COMServer
//

// This file will be processed by the MIDL tool to
// produce the type library (COMServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C1560521-EEAB-4776-9136-4148B5DA1E74),
	dual,
	nonextensible,
	pointer_default(unique),
	helpstring("IWelcome Interface"),
	custom (9BCFACEF-25AD-4A06-B241-47E89FB7ED08, "COMInteropExample.IWelcome")
]
interface IWelcome : IDispatch{
	[id(1), helpstring("method Greeting")] HRESULT Greeting([in] BSTR name, [out,retval] BSTR* message);
};

[
	object,
	uuid(17418E72-2F4C-41F2-B2D7-9027CEEDF24E),
	dual,
	nonextensible,
	pointer_default(unique),
	helpstring("IMath Interface"),
	custom (9BCFACEF-25AD-4A06-B241-47E89FB7ED08, "COMInteropExample.IMath")
]
interface IMath : IDispatch{
	[id(1), helpstring("method Add")] HRESULT Add([in] long val1, [in] long val2,
		[out,retval] long* result);
	[id(2), helpstring("method Sub")] HRESULT Sub([in] long val1, [in] long val2,
		[out, retval] long* result);
};

[
	uuid(D3443E8F-36BF-4E67-96E9-B51E7BCA83C2),
	version(1.0),
]
library COMServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(8E72DCFB-57DB-4384-A398-0FD8FE10AEB0),
		helpstring("COMDemo Class"),
		custom (9BCFACEF-25AD-4A06-B241-47E89FB7ED08, "COMInteropExample.COMDemo")
	]
	coclass COMDemo
	{
		[default] interface IWelcome;
		interface IMath;
	};
};

